# GRPC contains the General RPC module.
module GRPC
  #
  # Represents a registry of added interceptors available for enumeration.
  # The registry can be used for both server and client interceptors.
  # This class is internal to gRPC and not meant for public usage.
  #
  class InterceptorRegistry
    #
    # An error raised when an interceptor is attempted to be added
    # that does not extend GRPC::Interceptor
    #
    class DescendantError < StandardError
    end

    #
    # Initialize the registry with an empty interceptor list
    # This is an EXPERIMENTAL API.
    #
    def initialize: (?untyped interceptors) -> void

    #
    # Builds an interception context from this registry
    #
    # @return [InterceptionContext]
    #
    def build_context: () -> untyped
  end
end
