module WEBrick
  module HTTPAuth
    module Authenticator
      RequestField: "Authorization"

      ResponseField: "WWW-Authenticate"

      ResponseInfoField: "Authentication-Info"

      AuthException: untyped

      AuthScheme: nil

      attr_reader realm: untyped

      attr_reader userdb: untyped

      attr_reader logger: untyped

      private

      def check_init: (untyped config) -> untyped

      def check_scheme: (untyped req) -> (nil | untyped)

      def log: (untyped meth, untyped fmt, *untyped args) -> untyped

      def error: (untyped fmt, *untyped args) -> (untyped | nil)

      def info: (untyped fmt, *untyped args) -> (untyped | nil)
    end

    module ProxyAuthenticator
      RequestField: "Proxy-Authorization"

      ResponseField: "Proxy-Authenticate"

      InfoField: "Proxy-Authentication-Info"

      AuthException: untyped
    end
  end
end
