module WEBrick
  module HTTPAuth
    class BasicAuth
      include Authenticator

      AuthScheme: "Basic"

      def self.make_passwd: (untyped realm, untyped user, untyped pass) -> untyped

      attr_reader realm: untyped

      attr_reader userdb: untyped

      attr_reader logger: untyped

      def initialize: (untyped config, ?untyped default) -> void

      def authenticate: (untyped req, untyped res) -> untyped

      def challenge: (untyped req, untyped res) -> untyped
    end

    class ProxyBasicAuth < BasicAuth
      include ProxyAuthenticator
    end
  end
end
