module WEBrick
  module HTTPAuth
    class Htgroup
      def initialize: (untyped path) -> void

      def reload: () -> (untyped | nil)

      def flush: (?untyped? output) -> untyped

      def members: (untyped group) -> untyped

      def add: (untyped group, untyped members) -> untyped
    end
  end
end
