module WEBrick
  module HTTPAuth
    class Htpasswd
      include UserDB

      def initialize: (untyped path, ?password_hash: untyped?) -> void

      def reload: () -> untyped

      def flush: (?untyped? output) -> untyped

      def get_passwd: (untyped realm, untyped user, untyped reload_db) -> untyped

      def set_passwd: (untyped realm, untyped user, untyped pass) -> untyped

      def delete_passwd: (untyped realm, untyped user) -> untyped

      def each: () { (untyped) -> untyped } -> untyped
    end
  end
end
