module WEBrick
  module HTTPServlet
    class HTTPServletError < StandardError
    end

    class AbstractServlet
      def self.get_instance: (untyped server, *untyped options) -> untyped

      def initialize: (untyped server, *untyped options) -> void

      def service: (untyped req, untyped res) -> untyped

      def do_GET: (untyped req, untyped res) -> untyped

      def do_HEAD: (untyped req, untyped res) -> untyped

      def do_OPTIONS: (untyped req, untyped res) -> untyped

      private

      def redirect_to_directory_uri: (untyped req, untyped res) -> (untyped | nil)
    end
  end
end
