module WEBrick
  module AccessLog
    class AccessLogError < StandardError
    end

    CLF_TIME_FORMAT: "[%d/%b/%Y:%H:%M:%S %Z]"

    COMMON_LOG_FORMAT: "%h %l %u %t \"%r\" %s %b"

    CLF: untyped

    REFERER_LOG_FORMAT: "%{Referer}i -> %U"

    AGENT_LOG_FORMAT: "%{User-Agent}i"

    COMBINED_LOG_FORMAT: ::String

    def self?.setup_params: (untyped config, untyped req, untyped res) -> untyped

    def self?.format: (untyped format_string, untyped params) -> untyped

    def self?.escape: (untyped data) -> untyped
  end
end
