module WEBrick
  class Cookie
    attr_reader name: untyped

    attr_accessor value: untyped

    attr_accessor version: untyped

    #
    # The cookie domain
    attr_accessor domain: untyped

    attr_accessor path: untyped

    attr_accessor secure: untyped

    attr_accessor comment: untyped

    attr_accessor max_age: untyped

    def initialize: (untyped name, untyped value) -> void

    def expires=: (untyped t) -> untyped

    def expires: () -> untyped

    def to_s: () -> untyped

    def self.parse: (untyped str) -> (untyped | nil)

    def self.parse_set_cookie: (untyped str) -> untyped

    def self.parse_set_cookies: (untyped str) -> untyped
  end
end
