module WEBrick
  class HTTPServerError < ServerError
  end

  class HTTPServer < ::WEBrick::GenericServer
    def initialize: (?::Hash[untyped, untyped] config, ?untyped default) -> void

    def run: (untyped sock) -> untyped

    def service: (untyped req, untyped res) -> untyped

    def do_OPTIONS: (untyped req, untyped res) -> untyped

    def mount: (untyped dir, untyped servlet, *untyped options) -> untyped

    def mount_proc: (untyped dir, ?untyped? proc) { () -> untyped } -> untyped

    def unmount: (untyped dir) -> untyped

    alias umount unmount

    def search_servlet: (untyped path) -> untyped


    def lookup_server: (untyped req) -> untyped

    def access_log: (untyped config, untyped req, untyped res) -> untyped

    #
    # Creates the HTTPRequest used when handling the HTTP
    # request. Can be overridden by subclasses.
    def create_request: (untyped with_webrick_config) -> untyped

    #
    # Creates the HTTPResponse used when handling the HTTP
    # request. Can be overridden by subclasses.
    def create_response: (untyped with_webrick_config) -> untyped

    class MountTable
      def initialize: () -> void

      def []: (untyped dir) -> untyped

      def []=: (untyped dir, untyped val) -> untyped

      def delete: (untyped dir) -> untyped

      def scan: (untyped path) -> ::Array[untyped]

      private

      def compile: () -> untyped

      def normalize: (untyped dir) -> untyped
    end
  end
end
