module WEBrick
  class HTTPVersion
    include Comparable

    attr_accessor major: untyped

    attr_accessor minor: untyped

    def self.convert: (untyped version) -> untyped

    def initialize: (untyped version) -> void

    def <=>: (untyped other) -> untyped

    def to_s: () -> untyped
  end
end
