# GRPC contains the General RPC module.
module GRPC
  # GoogleRpcStatusUtils provides utilities to convert between a
  # GRPC::Core::Status and a deserialized Google::Rpc::Status proto
  # Returns nil if the grpc-status-details-bin trailer could not be
  # converted to a GoogleRpcStatus due to the server not providing
  # the necessary trailers.
  # Raises an error if the server did provide the necessary trailers
  # but they fail to deseriliaze into a GoogleRpcStatus protobuf.
  class GoogleRpcStatusUtils
    def self.extract_google_rpc_status: (untyped status) -> (nil | untyped)
  end
end
