# GRPC contains the General RPC module.
module GRPC
  # DefaultLogger is a module included in GRPC if no other logging is set up for
  # it.  See ../spec/spec_helpers an example of where other logging is added.
  module DefaultLogger
    def logger: () -> untyped

    private

    # NoopLogger implements the methods of Ruby's conventional logging interface
    # that are actually used internally within gRPC with a noop implementation.
    class NoopLogger
      def info: (untyped _ignored) -> nil

      def debug: (untyped _ignored) -> nil

      def warn: (untyped _ignored) -> nil
    end

    LOGGER: untyped
  end

  # Inject the noop #logger if no module-level logger method has been injected.
  extend DefaultLogger
end
