name: Lint Ruby

# tmp
# tmp2
on:
  push:
    branches:
    - master
    - feature/tmp/steep2
    paths:
    - "**/*.rb"
    - "**/*.gemspec"
    - ".github/workflows/lint.yml"
  pull_request:
    paths:
    - "**/*.rb"
    - "**/*.gemspec"
    - ".github/workflows/lint.yml"

jobs:
  rubocop:
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: "gemfiles/rubocop.gemfile"
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1
        bundler-cache: true
    - name: Lint Ruby code with RuboCop
      run: |
        bundle exec rubocop
  steep:
    runs-on: ubuntu-latest
    env:
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
      BUNDLE_FORCE_RUBY_PLATFORM: 1
      CI: true
    strategy:
      matrix:
        ruby: ["3.2"]
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run Steep
      run: |
        bundle exec rbs collection install
        bundle exec rake steep
